[package]
name = "termesh-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
termesh-core.workspace = true
base64.workspace = true
thiserror.workspace = true
